### BERT

- open source ML framework for NLP
- Bidirectional Encoder Representations from Transformers
- designed to help computers understand the meaning of ambiguous language in text by using surrounding text to establish context
- BERT framework was pre-trained using text from Wikipedia and can be fine-tuned with question and answers dataset
- LMs could read only text input sequentially - either left to right or vice-versa but not at the same time.
- BERT is different because of design to read in both direction at once. Capability got introduced by transformers called as Bidirectional.

Key Takeaway: It is based on Transformer architecture

In [1]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification

In [2]:
# Load pre-trained model and tokenizer
model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForSequenceClassification.from_pretrained(model_name,num_labels=2)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [9]:
texts = ['This was an amazing product.','This is the worst thing I have ever bought.']

In [22]:
# Tokenize the text
inputs = tokenizer(texts,return_tensors='tf',padding=True,truncation=True,max_length=28)

In [27]:
#Get the modela predictions
outputs = model(inputs)
predictions = tf.argmax(outputs.logits,axis=-1)

In [28]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.11811709, 0.61368865],
       [0.171668  , 0.76433206]], dtype=float32)>, hidden_states=None, attentions=None)

In [29]:
import numpy as np
np.array(predictions)

array([1, 1], dtype=int64)

In [30]:
labels = ['Negative', 'Positive']
for text, prediction in zip(texts, predictions):
    print(f'Text: {text}')
    print(f'Sentiment: {labels[prediction]}')

Text: This was an amazing product.
Sentiment: Positive
Text: This is the worst thing I have ever bought.
Sentiment: Positive
